version: '3'
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    networks:
      - bitdb
    volumes:
       - ./mongo:/data/db
  bitcoin-abc:
    build:
      context: "./docker"
      dockerfile: "./Dockerfile.bitcoin-abc"
    image: bitcoin-abc
    container_name: bitcoin-abc
    command: bitcoind
    networks:
      - bitdb
    restart: always
    ports:
      - 8333:8333
    volumes:
       - ./bitcoin:/root/.bitcoin
  bitdb:
    build:
      context: "./docker"
      dockerfile: "./Dockerfile.bitdb"
    image: bitdb
    container_name: bitdb
    working_dir: "/bitdb"
    command: bash -c "sleep 60 && npm start"
    restart: always
    networks:
      - bitdb
    depends_on:
      - mongo
      - bitcoin-abc
  bitserve:
    build:
      context: "./docker"
      dockerfile: "./Dockerfile.bitserve"
    image: bitserve
    container_name: bitserve
    working_dir: "/bitserve"
    command: bash -c "sleep 10 && npm start"
    restart: always
    networks:
      - bitdb
    depends_on:
      - mongo
    ports:
      - 3000:3000

networks:
  bitdb:
